uploads = []
generated = []

[[outputs]]
id = "ZpyaPHgNf1F6oMmV-QsIL"
uri = "file://JoyedTiers-region-wl.txt"
type = "text"
title = "JoyedTiers-region-wl.sk — Wins, Losses & Region Skript"

[[outputs]]
id = "BxEBUREXTXbRxAZcyj1o3"
uri = "file://JoyedTiers.txt"
type = "text"
title = "JoyedTiers.sk — Drop into plugins/Skript/scripts/"

[[outputs]]
id = "vD0fdlMhJTGrC7pOkOH8G"
uri = "file://JoyedTiers-patch.txt"
type = "text"
title = "JoyedTiers-patch.sk — drop alongside elo1sk.sk"

[[outputs]]
id = "lPa7EBq9hc8LniYgotnwk"
uri = "file://elo1sk-joyedtiers.txt"
type = "text"
title = "elo1sk-joyedtiers.sk — updated with on join IP capture"
